### ISSUE TITLE
Atomic variables seems unnecessery 

### ISSUE THREAD

**Issue by ashtum** [klemens-morgenstern/sam#4]
A union of atomic and non-atomic variables is used for performance reasons.
For example, this is what is used for `mutex_impl`:
```C++
union
{
    bool locked_;
    std::atomic<bool> ts_locked_;
};
```
It seems we can use a regular variable and protect it with `internal_lock()` and there would be no noticeable performance difference, there are two scenarios:
1. When there is no need to trade safety:
In this case, calling `internal_lock()` is cheap already (because it is a conditional mutex).

2. When we are in a multi-threaded context and need trade safety:
Doing an atomic read-modify-write operation will not be much faster than holding a lock for the duration of a variable update.

Here are some measurements for `mutex_impl`:
The original one:
```BASH
Benchmark  no-mutex asio: 909087 us
Benchmark  no-mutex asem: 400558 us
Benchmark  mutexed asio: 2320754 us
Benchmark  mutexed asem: 1953563 us
```

After removing the union and using a regular variable and protecting it with `internal_lock()`:
```BASH
Benchmark  no-mutex asio: 904121 us
Benchmark  no-mutex asem: 531338 us
Benchmark  mutexed asio: 2237703 us
Benchmark  mutexed asem: 1720310 us
```

**Comment by klemens-morgenstern** [comment]
Yeah, they're counter-productive it seems
